from typing import Any, Type, TypeVar, List, Dict, Optional
from uuid import UUID

T = TypeVar("T", bound="Domain")

class Domain:
    id: UUID

    def __init__(self, **kwargs) -> None: ...
    @classmethod
    def find(cls: Type[T], **kwargs) -> Optional[T]: ...
    @classmethod
    def find_all(cls: Type[T], **kwargs) -> List[T]: ...
    def save(self) -> T: ...
    def update(self, **kwargs) -> T: ...
    def persist(self) -> T: ...
    def sync(self, dto: Any) -> None: ...
    def encapsulate_nested(self) -> T: ...
    @classmethod
    def joint_find(cls: Type[T], query: str, params: Dict[str, Any] | None = None) -> List[T]: ...
    @classmethod
    def call_dao_method(cls, method: str, *args, **kwargs) -> Any: ...